import scriptwriter
from tokenizer import Token

class Translator:


	def __init__(self, function):
		self.function = function

	def rewriteArguments(self):
		for option in self.function.argList:
			for argument in option:
				if argument.tokenType == Token.TOKEN_VAR:
					argName = argument.val2
					newVal = self.argumentMapping.get(argName, None)
					if newVal != None:
						argument.val2 = newVal
						argument.tokenType = Token.TOKEN_CONST
					
	def writeFunction(self):
		funName = self.function.functionName
		self.rewriteArguments()
		translationFunction =self.functionMapping.get(funName.lower(), lambda function, parsedArgs: UnknownFunction(None, function))
		return translationFunction(self.function, None) 
		
	def IsActionRef(function, parsedArgs):
		return [Translator.getArg(function, 0) + " == akTargetRef"], Translator.setArgTypes(function, [0], ["Actor"])

	def NotImplemented(function, parsedArgs):
		funCall = ""
		if function.target != None:
			funCall += function.target + "."
		funCall += function.functionName + "("
		for i in range(0, len(function.argList)):
			funCall += Translator.getArg(function, i) + ", "
		
		if funCall[-1] == " ":
			funCall = funCall[:-2]
		funCall +=  ")"

		return [funCall], None
		
	argumentMapping = {
		"player" : "Game.GetPlayer()"
	}

	def setArgTypes(function, argNumber, enforcedType):
		pass

	def getArg(function, argNumber):
		textFunction = ""
		for argument in function.argList[argNumber]:
			if argument.val1 == None and argument.tokenType in [Token.TOKEN_VAR, Token.TOKEN_CONST]:
				textFunction += argument.val2 + " "
			elif argument.tokenType in [Token.TOKEN_VAR, Token.TOKEN_CONST]:
				textFunction += argument.val1 + "." + argument.val2 + " "
			else:
				textFunction += argument.val1
		if textFunction[-1] == " ":
			textFunction = textFunction[:-1]
		return textFunction

	functionMapping = {
		"abs" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"activate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addachievement" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addcreaturetoleveledlist" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addformtoformlist" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"additem" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"additemhealthpercent" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"additemtoleveledlist" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addnote" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addnpctoleveledlist" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addperk" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addscriptpackage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addspecialpoints" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addspell" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addtagskills" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addtofaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"addtopic" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"advancepclevel" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"agerace" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"applyimagespacemodifier" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"attachashpile" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"autodisplayobjectives" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"autosave" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"cast" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"castimmediateonself" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"clearactorsfactionsplayerenemyflag" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"cleardestruction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"clearfactionplayerenemyflag" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"clearnoactivationsound" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"clearownership" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"completeallobjectives" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"completequest" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"cos" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"createdetectionevent" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"damageactorvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"damageav" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"damageobject" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"disable" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"disableallactors" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"disableallmines" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"disablenavmesh" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"disableplayercontrols" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"dispel" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"dispelallspells" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"drop" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"dropme" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"duplicateallitems" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"enable" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"enablefasttravel" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"enablenavmesh" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"enableplayercontrols" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"entertrigger" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"equipitem" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"essentialdeathreload" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"evaluatepackage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"evaluatespellconditions" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"exists" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"exitgame" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"fadesfx" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"fireweapon" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"forceactivequest" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"forceactorvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"forceflee" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"forceradiostationupdate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"forcesave" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"forceterminalback" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"forceweather" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"frienddispositionboost" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getactionref" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getactoraggroradiusviolated" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getactorcrimeplayerenemy" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getactorfactionplayerenemy" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getactorsinhigh" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getactorvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getalarmed" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getangle" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getanimaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getarmorrating" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getattacked" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getav" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getbaseactorvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getbroadcaststate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getbuttonpressed" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getcannibal" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getcauseofdeath" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getclothingvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getcombattarget" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getconcussed" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getcontainer" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getcontainerinventorycount" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getcurrentaipackage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getcurrentaiprocedure" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getcurrenttime" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getcurrentweatherpercent" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdayofweek" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdead" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdeadcount" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdefaultopen" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdestroyed" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdestructionstage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdetected" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdetectionlevel" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdialogueemotion" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdialogueemotionvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdisabled" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdisposition" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getdistance" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getequipped" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getfactioncombatreaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getfactionrank" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getfactionrankdifference" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getfactionreaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getfactionrelation" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getforcerun" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getforcesneak" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getfriendhit" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getfurnituremarkerid" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getgamesetting" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getglobalvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getgold" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getgroupmembercount" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getgrouptargetcount" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"gethasnote" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getheadingangle" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"gethealthpercentage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"gethitlocation" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getidledoneonce" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getignorecrime" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getincell" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getinfaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getinsamecell" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getinworldspace" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getinzone" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisalerted" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisalignment" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisclass" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getiscreature" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getiscreaturetype" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getiscurrentpackage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getiscurrentweather" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisformtype" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisghost" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisid" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getislockbroken" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisobjecttype" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisplayablerace" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisrace" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisreference" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getissex" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisuseditem" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisuseditemequiptype" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getisvoicetype" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getitemcount" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getkillingblowlimb" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getknockedstate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getlasthitcritical" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getlastplayeraction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getlevel" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getlinkedref" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getlocked" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getlocklevel" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getlos" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getmajorcrimecount" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getmapmarkervisible" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getminorcrimecount" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getobjectivecompleted" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getobjectivedisplayed" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getoffersservicesnow" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getopenstate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getpackagetarget" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getparentref" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getpcenemyoffaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getpcexpelled" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getpcinfaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getpcisrace" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getpcissex" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getpcmiscstat" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getpcsleephours" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getpermanentactorvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getplantedexplosive" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getplayercontrolsdisabled" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getplayergrabbedref" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getplayername" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getplayerteammate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getplayerteammatecount" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getpos" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getquestcompleted" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getquestrunning" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getquestvariable" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getradiationlevel" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getrandompercent" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getrestrained" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getsandman" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getscale" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getscriptvariable" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getsecondspassed" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getself" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getshouldattack" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getsitting" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getsleeping" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getstage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getstagedone" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getstartingangle" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getstartingpos" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"gettalkedtopc" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getthreatratio" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"gettimedead" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"gettrespasswarninglevel" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getunconscious" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getuseditemactivate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatsbackareafree" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatsbacktargetvisible" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatsfrontareafree" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatsfronttargetvisible" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatsleftareafree" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatslefttargetvisible" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatsmode" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatsrightareafree" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatsrighttargetvisible" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatstargetheight" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getvatsvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getwalkspeed" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getweaponanimtype" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getweaponhealthperc" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getwindspeed" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"getxpfornextlevel" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"hasbeeneaten" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"hasfrienddisposition" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"hasloaded3d" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"hasmagiceffect" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"hasperk" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"ignorecrime" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isactionref" : lambda function, parsedArgs: Translator.IsActionRef(function, parsedArgs),
		"isactor" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isactoravictim" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isactordetected" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isactorevil" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isactortalkingthroughactivator" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isanimplaying" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iscellowner" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"ischild" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iscloudy" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iscombattarget" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iscontinuingpackagepcnear" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iscurrentfurnitureobj" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iscurrentfurnitureref" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isessential" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isfacingup" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isgoredisabled" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isgreetingplayer" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isguard" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"ishardcore" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isidleplaying" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isimagespaceactive" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isincombat" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isincriticalstage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isininterior" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isinlist" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isinmyownedcell" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iskiller" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iskillerobject" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"islastidleplaying" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isleftup" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"islimbgone" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"ismoving" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isowner" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"ispc1stperson" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"ispcamurderer" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"ispcsleeping" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isplayeractionactive" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isplayergrabbedref" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isplayermovingintonewspace" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isplayertagskill" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"ispleasant" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isps3" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"israining" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isrunning" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"issneaking" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"issnowing" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isspelltarget" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isswimming" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"istalking" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"istalkingactivatoractor" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"istimepassing" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"istorchout" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"istrespassing" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isturning" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iswaiting" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iswaterobject" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isweaponinlist" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isweaponout" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isweaponskilltype" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"iswin32" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"isxbox" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"kill" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"killactor" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"killallactors" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"lock" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"log" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"look" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"loopgroup" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"markfordelete" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"matchfacegeometry" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"matchrace" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"menumode" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"modactorvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"modav" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"modbartergold" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"moddisposition" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"modfactionrank" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"modfactionreaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"modpcattribute" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"modpcmiscstat" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"modpcskill" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"modscale" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"modweaponhealthperc" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"moveto" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"openteammatecontainer" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"pickidle" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"pipboyradio" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"pipboyradiooff" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"placeatme" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"placeatmehealthpercent" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"placeleveledactoratme" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"playbink" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"playgroup" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"playidle" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"playmagiceffectvisuals" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"playmagicshadervisuals" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"playmusic" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"playsound" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"playsound3d" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"preloadmagiceffect" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"purgecellbuffers" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"pushactoraway" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"releaseweatheroverride" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removeallitems" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removefromallfactions" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removefromfaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removeimagespacemodifier" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removeitem" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removeme" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removemerchantcontainer" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removenote" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removeperk" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removescriptpackage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"removespell" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"reset3dstate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"resetai" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"resetfalldamagetimer" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"resethealth" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"resetinterior" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"resetinventory" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"resetpipboymanager" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"resetquest" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"restoreactorvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"resurrectactor" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"return" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"rewardkarma" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"rewardxp" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"rotate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"samefaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"samefactionaspc" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"samerace" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"sameraceaspc" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"samesex" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"samesexaspc" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"say" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"sayto" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"scripteffectelapsedseconds" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"sendassaultalarm" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"sendtrespassalarm" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setactoralpha" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setactorfullname" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setactorsai" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setactorvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setalert" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setallreachable" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setallvisible" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setally" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setangle" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setatstart" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setaudiomultithreading" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setbartergold" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setbroadcaststate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setcellfullname" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setcellimagespace" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setcellownership" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setcellpublicflag" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setclass" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setcombatstyle" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setcriticalstage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setdefaultopen" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setdestroyed" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setdisposition" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setenemy" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setessential" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setfactionrank" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setfactionreaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setforcerun" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setforcesneak" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setghost" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setglobaltimemultiplier" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setignorefriendlyhits" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setimagespace" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setinchargen" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setitemvalue" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setlastextdooractivated" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setlevel" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setlocationspecificloadscreensonly" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setmerchantcontainer" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setminimaluse" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setnoactivationsound" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setnoavoidance" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setnpcradio" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setobjectivecompleted" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setobjectivedisplayed" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setopenstate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setownership" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setpackduration" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setpccanusepowerarmor" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setpcenemyoffaction" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setpcexpelled" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setpcsleephours" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setpctoddler" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setpcyoung" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setplayertagskill" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setplayerteammate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setpos" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setquestdelay" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setquestobject" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setrestrained" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setrigidbodymass" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setrumble" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setscale" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setsceneiscomplex" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setshowquestitems" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setsize" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setspecialpoints" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setstage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"settagskills" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"settalkingactivatoractor" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setunconscious" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setvatstarget" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setweaponhealthperc" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setweather" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"setzonerespawns" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"sexchange" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showallmapmarkers" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showbarbermenu" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showbartermenu" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showdialogsubtitles" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showmap" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showmessage" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"shownamemenu" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showplasticsurgeonmenu" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showracemenu" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showrepairmenu" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showsleepwaitmenu" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showspecialbookmenuparams" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showtutorialmenu" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showviewerstrings" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"showwarning" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"sin" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"skipanim" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"sqrt" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"startcannibal" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"startcombat" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"startconversation" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"startmasterfileseekdata" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"startmistersandman" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"startquest" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"startradioconversation" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"stopcombat" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"stopcombatalarmonactor" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"stoplook" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"stopmagiceffectvisuals" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"stopmagicshadervisuals" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"stopquest" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"stopwaiting" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"systemsave" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"tan" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"togglemotionblur" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"trapupdate" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"triggerhitshader" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"triggerhudshudder" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"triggerscreenblood" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"unequipitem" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"unlock" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"useweapon" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"wait" : lambda function, parsedArgs: Translator.NotImplemented(function, parsedArgs),
		"wakeuppc" : lambda function, parsedArgs: Translator.NotImplemented(function)
	}
